
const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_MESSAGE = "NEW_MESSAGE"; 
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const DELETE_MESSAGES_ALERT = "DELETE_MESSAGES_ALERT";
const DELETE_ALL_MESSAGES_ALERT = "DELETE_ALL_MESSAGES_ALERT";

export { 
    ALERT, 
    REFETCH_CHATS , 
    NEW_MESSAGE_ALERT, 
    NEW_REQUEST, 
    NEW_MESSAGE,
    START_TYPING,
    STOP_TYPING,
    DELETE_MESSAGES_ALERT,
    DELETE_ALL_MESSAGES_ALERT,
};




