const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_REQUEST = "NEW_REQUEST";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"

const REFETCH_CHATS = "REFETCH_CHATS";
const ALERT = "ALERT";

const DELETE_MESSAGES_ALERT = "DELETE_MESSAGES_ALERT";
const DELETE_ALL_MESSAGES_ALERT = "DELETE_ALL_MESSAGES_ALERT";


export { NEW_MESSAGE, NEW_REQUEST, NEW_MESSAGE_ALERT, START_TYPING, STOP_TYPING, REFETCH_CHATS, ALERT, DELETE_MESSAGES_ALERT, DELETE_ALL_MESSAGES_ALERT};