const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_REQUEST = "NEW_REQUEST";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"

export { NEW_MESSAGE, NEW_REQUEST, NEW_MESSAGE_ALERT, START_TYPING, STOP_TYPING};